# GitHub Actions workflow for PublicIPWatcher
# Builds and publishes releases automatically

name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore IPNotification/IPNotification.csproj

    - name: Build application
      run: dotnet build IPNotification/IPNotification.csproj -c Release --no-restore

    - name: Publish self-contained executable
      run: |
        dotnet publish IPNotification/IPNotification.csproj `
          -c Release `
          -r win-x64 `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          -p:PublishTrimmed=false `
          -o ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PublicIPWatcher-${{ github.sha }}
        path: ./publish/IPNotification.exe
        retention-days: 30

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
      actions: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Get version from tag
      id: get_version
      run: |
        $version = $env:GITHUB_REF -replace 'refs/tags/v', ''
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        echo "Version: $version"

    - name: Publish release build
      run: |
        dotnet publish IPNotification/IPNotification.csproj `
          -c Release `
          -r win-x64 `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          -p:PublishTrimmed=false `
          -o ./release-build

    - name: Create release archive
      run: |
        Compress-Archive -Path ./release-build/IPNotification.exe -DestinationPath ./PublicIPWatcher-v${{ steps.get_version.outputs.VERSION }}-win-x64.zip

    - name: Generate release notes
      id: release_notes
      run: |
        $notes = @"
        ## PublicIPWatcher v${{ steps.get_version.outputs.VERSION }}
        
        ### Installation
        1. Download the ZIP file below
        2. Extract IPNotification.exe to any folder
        3. Run IPNotification.exe (no installation required)
        
        ### Features
        - Monitor your public IP address automatically
        - System tray integration
        - Configurable check intervals
        - Change notifications
        - IP history tracking
        
        ### Requirements
        - Windows 10 or later
        - No .NET installation required (self-contained)
        
        ### File Information
        - **File**: IPNotification.exe
        - **Type**: Self-contained executable
        - **Size**: ~30MB (includes .NET runtime)
        "@
        
        # Save to file for GitHub release
        $notes | Out-File -FilePath release-notes.md -Encoding utf8

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./PublicIPWatcher-v${{ steps.get_version.outputs.VERSION }}-win-x64.zip
        body_path: release-notes.md
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
